/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
/* Header for class ayush_practice_facedetection2_OpenCvNative */

using namespace cv;
#ifndef _Included_ayush_practice_facedetection2_OpenCvNative
#define _Included_ayush_practice_facedetection2_OpenCvNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ayush_practice_facedetection2_OpenCvNative
 * Method:    faceDetection
 * Signature: (J)V
 */
void detect(Mat& frame);
JNIEXPORT void JNICALL Java_ayush_practice_facedetection2_OpenCvNative_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
